server:
  port: 18081

grpc:
  client:
    user-service:
      address: "static://localhost:19090"
      negotiationType: plaintext

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: blubin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone=Asia/Ho_Chi_Minh:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#              client-id: ${GOOGLE_CLIENT_ID}
#              client-secret: ${GOOGLE_CLIENT_SECRET}
#
#              scope:
#                - profile
#                - email
#              redirect-uri: "http://localhost:8081/login/oauth2/code/google"
#              client-name: Google
#              authorization-grant-type: authorization_code
#              client-authentication-method: client_secret_basic
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
#            scope: user:email
#            redirect-uri: "${baseUrl}/login/oauth2/code/github"
#            client-name: GitHub
#            authorization-grant-type: authorization_code
#            client-authentication-method: basic
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc0MDkzOTAzNCwiaWF0IjoxNzQwOTM5MDM0fQ.RaE-tYEFCkPbFo-VKgz4YPHOh9RvKpCN40SpxoiCzms

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "Content-Type"
    - "Authorization"
  allow-credentials: true
  max-age: 3600


resilience4j.circuitbreaker:
  instances:
    countryServiceCircuitBreaker:
      registerHealthIndicator: true
      failureRateThreshold: 50
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10