server:
  port: 18084

spring:
  application:
    name: promotion_service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: blubin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:18081  # Địa chỉ máy chủ Identity (Keycloak, Auth0, hoặc service cấp JWT)
            jwk-set-uri: http://localhost:18081/access-token-cookie  # Endpoint cung cấp public key để xác thực token


management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    countryServiceCircuitBreaker:
      registerHealthIndicator: true
      failureRateThreshold: 50 #
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10