server:
  port: 18085

spring:
  application:
    name: cart_service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: blubin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j.circuitbreaker:
  instances:
    countryServiceCircuitBreaker:
      registerHealthIndicator: true
      failureRateThreshold: 50 #
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10