name: GitHub API Cronjob

on:
  schedule:
    - cron: '*/5 * * * *'  # chạy mỗi phút
  workflow_dispatch:     # cho phép chạy thủ công

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Run 
        run: echo "$(date) - Sending request to GitHub API"

      - name: Gọi GitHub API
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/masan-group/copilot/metrics
          
      - name: Save file
        uses: actions/upload-artifact@v4
        with:
         name: github-api-log
         path: my_log.txt
